disabled_rules: # rule identifiers to exclude from running
  - nesting
opt_in_rules: # some rules are only opt-in
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  # - Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods