language: objective-c
osx_image: xcode7.3
branches:
  only:
    - master
xcode_workspace: ParrotStatus.xcworkspace
xcode_scheme: "Tests"
script: xcodebuild -workspace ParrotStatus.xcworkspace -scheme "Tests" clean test | xcpretty --test -t
xcode_sdk: macosx10.11
before_install:
  - brew update
  - gem install activesupport -v  '= 4.2.6'
  - gem install xcpretty
  - gem install cocoapods -v '1.1.1'
cache: cocoapods
install:
    - pod install --repo-update
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7699ccd2c005aaff3a91
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
